In [59]:
import pandas as pd
import numpy as np

In [60]:
station_code = pd.read_excel("../空氣品質監測站基本資料(含地理圖資).xlsx")

In [61]:
station_code

,SiteName,SiteEngName,AreaName,County,Township,SiteAddress,TWD97Lon,TWD97Lat,SiteType
0,臺東,Taitung,花東空品區,臺東縣,臺東市,臺東市中山路276號,121.150450,22.755358,一般測站
1,臺南,Tainan,雲嘉南空品區,臺南市,中西區,臺南市中西區南寧街45號,120.202617,22.984581,一般測站
2,臺西,Taixi,雲嘉南空品區,雲林縣,臺西鄉,雲林縣臺西鄉五港路505號,120.202842,23.717533,工業測站
3,觀音,Guanyin,北部空品區,桃園市,觀音區,桃園市觀音區文化路2號,121.082761,25.035503,背景測站
4,關山,Guanshan,花東空品區,臺東縣,關山鎮,臺東縣關山鎮自強路66號,121.161933,23.045083,其它測站
...,...,...,...,...,...,...,...,...,...
71,士林,Shilin,北部空品區,臺北市,北投區,臺北市北投區文林北路155號,121.515389,25.105417,一般測站
72,土城,Tucheng,北部空品區,新北市,土城區,新北市土城區學府路一段241號,121.451861,24.982528,一般測站
73,三義,Sanyi,竹苗空品區,苗栗縣,三義鄉,苗栗縣三義鄉西湖村上湖61-1號,120.758833,24.382942,一般測站
74,三重,Sanchong,北部空品區,新北市,三重區,新北市三重區三和路重陽路交口,121.493806,25.072611,交通測站
75,二林,Erlin,中部空品區,彰化縣,二林鎮,彰化縣二林鎮萬合里江山巷1號,120.409653,23.925175,一般測站

In [62]:
f = open("../空氣品質監測月值.csv")
lines = f.readlines()
f.close()
f_2 = open("../空氣品質監測月值_mod2.csv", "w+")
for line in lines:
    f_2.write(line.replace("	",",").replace("\"",""))
f_2.close()

'\nf = open("../空氣品質監測月值.csv")\nlines = f.readlines()\nf.close()\nf_2 = open("../空氣品質監測月值_mod2.csv", "w+")\nfor line in lines:\n    f_2.write(line.replace("\t",",").replace(""",""))\nf_2.close()\n'

In [63]:
air_pollution = pd.read_excel("../空氣品質監測月值_mod2.xlsx")

In [75]:
air_pollution
air_pollution = air_pollution.drop_duplicates()
air_pollution.reindex()
air_pollution.to_excel("../空氣品質監測月值_mod3.xlsx", index=None)

In [76]:
air_pollution = pd.read_excel("../空氣品質監測月值_mod3.xlsx")

In [114]:
air_pollution = air_pollution[air_pollution.Concentration != "x"]

In [65]:
district_code = pd.read_excel("../行政區中心點.xlsx")

In [66]:
district_code

,行政區名,_x0033_碼郵遞區號,中心點經度,中心點緯度,TGOS_URL
0,臺北市中正區,100,121.519884,25.032405,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
1,臺北市大同區,103,121.513042,25.063424,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
2,臺北市中山區,104,121.538160,25.069699,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
3,臺北市松山區,105,121.557588,25.059991,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
4,臺北市大安區,106,121.543445,25.026770,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
...,...,...,...,...,...
366,花蓮縣瑞穗鄉,978,121.407347,23.515612,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
367,花蓮縣萬榮鄉,979,121.318953,23.727726,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
368,花蓮縣玉里鎮,981,121.360448,23.371436,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
369,花蓮縣卓溪鄉,982,121.180422,23.390629,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...
370,花蓮縣富里鄉,983,121.298049,23.196721,http://tgos.nat.gov.tw/tgos/Web/MetaData/TGOS_...

In [115]:
air_pollution_index = air_pollution.copy()

In [116]:
air_pollution_index = air_pollution_index.drop(columns=["ItemId","ItemName","ItemEngName","ItemUnit","MonitorMonth"])

In [117]:
air_pollution_index = air_pollution_index.head(65)

In [118]:
air_pollution_index

    SiteId SiteName Concentration
0       50       鳳山            25
1       83       麥寮            17
2       80       關山             7
3       78       馬公            13
4        3       萬里            12
..     ...      ...           ...
60      28       豐原            14
61      27       三義            12
62      26       苗栗            16
63      84      富貴角            13
64       4       新店            11

[65 rows x 3 columns]

In [125]:
for i in range(0,len(air_pollution_index)):
    target = air_pollution_index.iat[i,1]
    df = air_pollution[air_pollution.SiteName == target].Concentration.tolist()
    result = sum(df)/len(df)
    air_pollution_index.iat[i,2] = result

In [126]:
air_pollution_index

    SiteId SiteName Concentration
0       50       鳳山       32.5882
1       83       麥寮       25.4369
2       80       關山        11.125
3       78       馬公       18.4167
4        3       萬里       16.9167
..     ...      ...           ...
60      28       豐原       23.3793
61      27       三義       21.6833
62      26       苗栗       24.3583
63      84      富貴角       15.6538
64       4       新店       18.9496

[65 rows x 3 columns]

In [135]:
TWD97Lon=[]
TWD97Lat=[]
for i in range(0,len(air_pollution_index)):
    target = air_pollution_index.iat[i,1]
    flag = 0
    for j in range(0,len(station_code)):
        if station_code.iat[j,0] == target:
            TWD97Lon.append(station_code.iat[j,6])
            TWD97Lat.append(station_code.iat[j,7])
            flag = 1
        if flag == 0 and j == len(station_code)-1:
            print(target)

富貴角

In [137]:
air_pollution_index = air_pollution_index.drop(63)

air_pollution_index['TWD97Lon'] = TWD97Lon
air_pollution_index['TWD97Lat'] = TWD97Lat

In [138]:
air_pollution_index

    SiteId SiteName Concentration    TWD97Lon   TWD97Lat
0       50       鳳山       32.5882  120.358083  22.627392
1       83       麥寮       25.4369  120.251825  23.753506
2       80       關山        11.125  121.161933  23.045083
3       78       馬公       18.4167  119.566158  23.569031
4        3       萬里       16.9167  121.689881  25.179667
..     ...      ...           ...         ...        ...
59      29       沙鹿       25.7083  120.568794  24.225628
60      28       豐原       23.3793  120.741711  24.256586
61      27       三義       21.6833  120.758833  24.382942
62      26       苗栗       24.3583  120.820200  24.565269
64       4       新店       18.9496  121.537778  24.977222

[64 rows x 5 columns]

In [139]:
import pykrige.kriging_tools as kt
from pykrige.ok import OrdinaryKriging

In [141]:
ok = OrdinaryKriging(
    air_pollution_index.TWD97Lon.tolist(),
    air_pollution_index.TWD97Lat.tolist(),
    air_pollution_index.Concentration.tolist(),
    variogram_model="linear",
    verbose=False,
    enable_plotting=False,
)

In [142]:
ok

In [159]:
ok.execute("grid",121.519884,25.032405)[0][0][0]

19.5787002446845

In [161]:
predict_list = []
for i in range(0,len(district_code)):
    x = district_code.iat[i,2]
    y = district_code.iat[i,3]
    predict_list.append(ok.execute("grid",x,y)[0][0][0])

In [162]:
predict_list

[19.5787015320047,
 19.587125386983622,
 19.27040918194396,
 19.092134596450332,
 19.31811243949504,
 19.813134704843193,
 19.006520511773434,
 18.82281389763116,
 18.945123693096974,
 18.667543227545316,
 18.622538868881172,
 18.99962468651332,
 17.570451041086326,
 17.42093713647506,
 17.393742986468553,
 17.617197966083136,
 17.740329803733253,
 17.579479778733067,
 17.92249629187604,
 18.0425955084917,
 18.19505822209416,
 25.0231148682914,
 24.7850982497315,
 25.092837634730152,
 23.155648505706164,
 20.184140210973755,
 18.182350536567945,
 18.55418311668373,
 18.28771242532985,
 17.170039414554836,
 17.50150463599246,
 17.048598078394363,
 16.67093479870848,
 19.334457236450735,
 17.6248085500637,
 18.909249434046423,
 19.619966889065658,
 19.834151926554227,
 20.183017778553793,
 20.146627250940128,
 20.45991726102594,
 20.700618127182278,
 19.865761267794767,
 20.28294423872689,
 20.324945645073992,
 20.491617476437412,
 19.83370220285861,
 20.045657559862512,
 19.953708867413948,
 19.276788318265012,
 18.71821338183475,
 18.40152222200839,
 17.00505589693393,
 16.84634299189279,
 17.330162294655047,
 16.767319113223913,
 17.77037327455185,
 16.8356446678899,
 17.639511846194992,
 18.855506038452088,
 16.6425768239192,
 16.866054636807544,
 16.43590800488157,
 17.586879884513944,
 14.33828835099911,
 22.570915089111423,
 22.35800804811993,
 22.700388078025572,
 22.346469973428636,
 22.071451322920126,
 22.325044763956985,
 21.84277321365087,
 21.315982928472657,
 21.729029969614842,
 22.31744412631351,
 21.875891473419326,
 21.57760643615831,
 21.487307394369246,
 20.6064876895515,
 21.970379801745295,
 22.274565247375367,
 21.35589866393817,
 21.339147892514045,
 21.248562631228985,
 21.71364328381186,
 21.974750457467138,
 21.729750725397132,
 20.934093152373052,
 20.65262436869433,
 20.973945297281645,
 20.837494258408817,
 20.088015998561307,
 21.261813140995272,
 20.933693415872256,
 22.965315419436376,
 22.772802705668084,
 22.64301995488421,
 22.354515758565267,
 23.003770984459962,
 23.60629530786879,
 24.154175533459707,
 24.475667066515854,
 23.5547512720202,
 23.122502743491395,
 23.135970517973114,
 23.425885195839367,
 23.592541003649437,
 22.260906501151595,
 23.7637204281307,
 24.057400401916013,
 23.825747890578057,
 23.880785207608252,
 26.086652425092936,
 26.01518633437182,
 26.326620057978722,
 26.164413760333943,
 25.96069746324832,
 25.421134137524874,
 26.081646397559318,
 26.418657533585012,
 25.64932109450467,
 26.33247878265636,
 26.46605784918875,
 26.744237943810827,
 24.928804204945745,
 24.73759407427022,
 24.544967345074404,
 24.351033257483266,
 21.99294633418159,
 24.838308990996236,
 25.379946746925988,
 25.69397467050444,
 25.251890676627298,
 26.621124138614405,
 25.922238953137516,
 26.33907297950772,
 26.0717121963533,
 25.60331451267227,
 24.9048191665536,
 24.918269727163583,
 25.20072554666549,
 27.037321067779185,
 27.205167434279467,
 27.337663894795075,
 27.44245213925756,
 27.213624916563024,
 27.51733730563864,
 26.907530917819287,
 26.92494769879342,
 26.664511436294546,
 27.6360424299047,
 27.873226484705164,
 27.97668378482085,
 27.827109701288258,
 27.912531951448912,
 27.552276521057724,
 27.71503013583481,
 28.15680325636056,
 28.26502992414637,
 28.12191732189549,
 28.26375691638914,
 28.470759884216303,
 28.36518338478578,
 28.095504551382867,
 28.096729123149515,
 27.84927941839712,
 28.20012890123604,
 27.406552243455074,
 26.60609455450153,
 26.71046449742301,
 25.4024994728847,
 24.796270560169283,
 22.4632529884048,
 27.72386746924514,
 26.787044301437934,
 25.960235650840993,
 25.2485801635706,
 23.64821506843088,
 27.64526273514754,
 26.885408932030778,
 29.10122618460383,
 28.952803408941246,
 27.799712865062524,
 27.909228478618985,
 28.123689876766562,
 26.171098994709524,
 28.353303768394106,
 27.55699971430651,
 29.06553270153491,
 29.03795882342127,
 29.029216423319635,
 28.872905596846632,
 28.629411194460086,
 28.79454565020791,
 28.93093781853456,
 28.991100164658008,
 28.90232648492951,
 28.938605911564814,
 29.04192712398073,
 28.890380649304497,
 28.908062257767572,
 28.90215149754023,
 28.809408081348263,
 28.705002003100134,
 28.436495440241266,
 28.223233074106943,
 27.943231273987138,
 28.400399388175543,
 27.941451031543505,
 28.79853031348825,
 28.434370907815417,
 28.33295888507705,
 28.70278784113065,
 28.678940952485338,
 28.54671479273416,
 28.68250157419237,
 28.566909549069106,
 28.29468778672981,
 28.222919727483557,
 28.677756325557187,
 29.975748433242057,
 30.006964259017508,
 30.17043287262195,
 29.900875392467253,
 30.01897656852875,
 29.782554895209604,
 29.765279192919266,
 30.037527609698063,
 29.490715311778178,
 29.064755967354856,
 28.534260420079196,
 28.05790872315375,
 27.768374405159918,
 30.192329363858043,
 29.820792993363817,
 29.506074353043537,
 29.120727517450717,
 29.356396830109734,
 29.410691631191284,
 29.519955064088,
 29.496474521878845,
 29.257387455692076,
 29.201589457351247,
 29.053762217255148,
 29.16203954217672,
 29.08069025725242,
 28.741491259490275,
 28.693542402454014,
 28.980363863888925,
 29.253993352854895,
 29.071013967619404,
 29.156819417361717,
 29.342591133331098,
 28.928769859075658,
 29.15086998628754,
 29.492877664697474,
 29.56353091353551,
 31.40686910414711,
 31.42217510317551,
 31.355825312504525,
 31.41508360237241,
 31.443063484394205,
 31.240583600138123,
 31.263761041525257,
 31.39694765379203,
 31.318026836415445,
 30.84161745090674,
 31.4222594074448,
 31.086969393604647,
 30.846844253756228,
 27.23148328760002,
 22.035237748293824,
 30.873434406647974,
 30.622544636689383,
 30.359927899806582,
 29.898810760145075,
 30.575261402789533,
 31.200557981627263,
 31.23140588582317,
 31.077770972045172,
 30.856986316901693,
 30.472476625569737,
 31.18864207000822,
 30.68680573901188,
 30.15141753626041,
 31.078417590892293,
 30.432384001082852,
 29.065819064868712,
 27.790406700256607,
 26.326077005674115,
 28.74798095636484,
 27.630646560080464,
 26.86064108647772,
 23.94674394419836,
 25.720416527642058,
 24.810151213039575,
 30.541810598568716,
 25.946463232659898,
 25.961664558094192,
 26.931632536024964,
 27.68551839902529,
 25.999129296375905,
 26.180272972625062,
 29.22559402916694,
 29.238209316744246,
 29.448914475676354,
 29.42634852233263,
 29.481202250318873,
 26.86092634592404,
 29.890123474310688,
 26.0373911567746,
 23.890341327253992,
 26.237586200084202,
 29.600392071214802,
 28.985655550732393,
 27.480146657609204,
 28.217128289761348,
 28.57009401100607,
 29.082181934338685,
 29.05994761813948,
 28.007380150961758,
 29.84277460122442,
 28.37595949659997,
 25.91418041227955,
 25.613429005979274,
 27.672623477617346,
 29.049989156299077,
 27.46092888875504,
 28.4562382298898,
 28.08997775400563,
 28.830880666996116,
 28.262729068851364,
 27.44538665764746,
 29.72922690225915,
 26.35463272771066,
 23.98641080522986,
 24.657975787157845,
 22.728964383177953,
 20.80064456928542,
 20.663953286258597,
 19.616325883380433,
 19.443941583265904,
 18.064980510089775,
 15.477090582223278,
 15.397872006183436,
 20.567106828545825,
 20.031551012894774,
 17.898330865432975,
 17.79814423335145,
 20.744746811229618,
 17.832502607623923,
 17.075917277566088,
 17.10333301867126,
 17.66482811329864,
 20.42491026374243,
 22.61407216059522,
 21.2060673075455,
 22.1941279683099,
 17.351999721138686,
 17.44315992989423,
 18.75354146158247,
 17.690433432734324,
 17.99230548198272,
 18.54019274608973,
 18.709063443281735,
 18.008986926775123,
 18.58841760727437,
 20.135536532340815,
 18.395126824803093,
 20.3728193208988,
 17.915631310752858]

In [163]:
predict_result = district_code.copy()

In [165]:
predict_result['predict_PM2.5'] = predict_list

In [166]:
predict_result.to_excel("../PM2.5行政區預測202009030.xlsx")